/**
 * 100 SEO blog topics for Cabzii content calendar.
 * Categories: airport taxi, outstation, travel guides, Chennai keywords, fare keywords.
 */
export const SEO_BLOG_TOPICS = [
  { slug: "chennai-airport-taxi-fare-guide-2026", title: "Chennai Airport Taxi Fare Guide 2026 — MAA Pickup & Drop Rates", category: "airport" },
  { slug: "how-to-book-airport-taxi-chennai-online", title: "How to Book Airport Taxi in Chennai Online (Step-by-Step)", category: "airport" },
  { slug: "chennai-airport-terminal-1-vs-terminal-4-pickup", title: "Chennai Airport Terminal Pickup Guide — Domestic & International", category: "airport" },
  { slug: "best-time-to-book-chennai-airport-cab", title: "Best Time to Book Chennai Airport Cab for Early Morning Flights", category: "airport" },
  { slug: "chennai-airport-to-omr-cab-fare", title: "Chennai Airport to OMR Cab Fare — Sedan vs SUV vs Innova", category: "fare" },
  { slug: "chennai-airport-to-anna-nagar-taxi-cost", title: "Chennai Airport to Anna Nagar Taxi Cost & Travel Time", category: "fare" },
  { slug: "chennai-airport-transfer-for-international-arrivals", title: "Chennai Airport Transfer Tips for International Arrivals", category: "airport" },
  { slug: "fixed-fare-vs-meter-airport-taxi-chennai", title: "Fixed Fare vs Meter: Which Is Better for Chennai Airport Taxi?", category: "fare" },
  { slug: "chennai-airport-pickup-with-flight-delay", title: "What Happens If Your Flight Is Delayed — Chennai Airport Pickup", category: "airport" },
  { slug: "innova-vs-sedan-chennai-airport-transfer", title: "Innova vs Sedan for Chennai Airport Transfer — Luggage Guide", category: "airport" },
  { slug: "chennai-to-bangalore-taxi-fare-one-way", title: "Chennai to Bangalore Taxi Fare — One Way Cab Price Breakdown", category: "fare" },
  { slug: "chennai-to-pondicherry-cab-fare-ecr-route", title: "Chennai to Pondicherry Cab Fare via ECR — 2026 Rates", category: "fare" },
  { slug: "chennai-to-tirupati-cab-cost-darshan-trip", title: "Chennai to Tirupati Cab Cost for One-Day Darshan Trip", category: "outstation" },
  { slug: "chennai-to-vellore-taxi-fare-cmc-visit", title: "Chennai to Vellore Taxi Fare for CMC & Hospital Visits", category: "fare" },
  { slug: "chennai-to-coimbatore-cab-price-highway-tips", title: "Chennai to Coimbatore Cab Price & NH Highway Travel Tips", category: "outstation" },
  { slug: "chennai-to-madurai-taxi-fare-family-trip", title: "Chennai to Madurai Taxi Fare for Family Temple Visits", category: "fare" },
  { slug: "one-way-cab-vs-round-trip-outstation-chennai", title: "One Way Cab vs Round Trip Outstation from Chennai — Which Saves More?", category: "outstation" },
  { slug: "outstation-cab-toll-charges-tamil-nadu", title: "Outstation Cab Toll Charges in Tamil Nadu — What to Expect", category: "fare" },
  { slug: "night-charges-outstation-cab-chennai", title: "Night Charges on Outstation Cabs from Chennai Explained", category: "fare" },
  { slug: "best-outstation-routes-from-chennai-weekend", title: "Best Weekend Outstation Routes from Chennai by Cab", category: "outstation" },
  { slug: "chennai-to-kodaikanal-cab-hill-station-guide", title: "Chennai to Kodaikanal Cab — Hill Station Travel Guide", category: "travel" },
  { slug: "chennai-to-ooty-taxi-route-and-fare", title: "Chennai to Ooty Taxi Route, Season & Fare Guide", category: "travel" },
  { slug: "chennai-to-rameswaram-cab-pilgrimage-guide", title: "Chennai to Rameswaram Cab — Pilgrimage Route Guide", category: "travel" },
  { slug: "chennai-to-kanyakumari-outstation-cab-itinerary", title: "Chennai to Kanyakumari Outstation Cab — 2-Day Itinerary", category: "travel" },
  { slug: "chennai-to-yercaud-weekend-cab-trip", title: "Chennai to Yercaud Weekend Cab Trip — Stops & Fares", category: "travel" },
  { slug: "chennai-local-taxi-hourly-packages-explained", title: "Chennai Local Taxi Hourly Packages — 4hr vs 8hr Explained", category: "chennai" },
  { slug: "cab-booking-chennai-without-app", title: "Cab Booking Chennai Without App — OTP Booking on cabzii.in", category: "chennai" },
  { slug: "taxi-service-chennai-near-me-how-it-works", title: "Taxi Service Chennai Near Me — How Online Pickup Works", category: "chennai" },
  { slug: "chennai-cab-booking-for-wedding-events", title: "Chennai Cab Booking for Weddings — Hourly & Full-Day Packages", category: "chennai" },
  { slug: "corporate-cab-booking-chennai-monthly", title: "Corporate Cab Booking in Chennai — Employee Transfer Tips", category: "chennai" },
  { slug: "chennai-cab-fare-dzire-vs-ertiga-vs-innova", title: "Chennai Cab Fare Comparison — Dzire vs Ertiga vs Innova", category: "fare" },
  { slug: "cheap-cab-booking-chennai-tips", title: "How to Get Cheap Cab Booking in Chennai Without Compromising Safety", category: "fare" },
  { slug: "chennai-taxi-fare-calculator-guide", title: "Chennai Taxi Fare Calculator — How Package Pricing Works", category: "fare" },
  { slug: "extra-km-charges-chennai-cab-rental", title: "Extra KM Charges on Chennai Cab Rental — Read Before Booking", category: "fare" },
  { slug: "chennai-cab-booking-peak-hour-surcharge", title: "Peak Hour Surcharge on Chennai Cab Booking — When It Applies", category: "fare" },
  { slug: "tempo-traveller-rental-chennai-group-travel", title: "Tempo Traveller Rental Chennai — 12 vs 17 Seater for Groups", category: "chennai" },
  { slug: "chennai-to-bengaluru-innova-crysta-fare", title: "Chennai to Bengaluru Innova Crysta Fare & Comfort Guide", category: "fare" },
  { slug: "chennai-to-hyderabad-outstation-cab-route", title: "Chennai to Hyderabad Outstation Cab — Route & Overnight Tips", category: "outstation" },
  { slug: "chennai-to-trichy-cab-srirangam-visit", title: "Chennai to Trichy Cab for Srirangam Temple Visit", category: "travel" },
  { slug: "chennai-to-salem-taxi-industrial-travel", title: "Chennai to Salem Taxi for Business & Industrial Travel", category: "outstation" },
  { slug: "madurai-to-chennai-cab-fare-reverse-route", title: "Madurai to Chennai Cab Fare — Reverse One Way Route", category: "fare" },
  { slug: "coimbatore-to-chennai-taxi-highway-guide", title: "Coimbatore to Chennai Taxi — Highway Stops & Fare Guide", category: "outstation" },
  { slug: "bengaluru-airport-taxi-booking-guide", title: "Bengaluru Airport Taxi Booking Guide — BLR Pickup & Drop", category: "airport" },
  { slug: "bengaluru-to-mysore-one-way-cab-fare", title: "Bengaluru to Mysore One Way Cab Fare — 2026 Rates", category: "fare" },
  { slug: "bengaluru-outstation-cab-weekend-getaways", title: "Best Outstation Cab Trips from Bengaluru for Weekends", category: "outstation" },
  { slug: "coimbatore-airport-taxi-cjb-fares", title: "Coimbatore Airport Taxi (CJB) Fares & Booking Tips", category: "airport" },
  { slug: "coimbatore-to-ooty-cab-hill-drive", title: "Coimbatore to Ooty Cab — Hill Drive Safety & Fare", category: "travel" },
  { slug: "madurai-airport-taxi-ixm-transfer", title: "Madurai Airport Taxi (IXM) — City Transfer Fares", category: "airport" },
  { slug: "madurai-to-rameswaram-cab-pilgrimage", title: "Madurai to Rameswaram Cab — Pilgrimage Day Trip Guide", category: "travel" },
  { slug: "trichy-airport-taxi-trz-pickup", title: "Trichy Airport Taxi (TRZ) Pickup & Drop Fares", category: "airport" },
  { slug: "trichy-to-chennai-cab-booking-tips", title: "Trichy to Chennai Cab Booking — Best Departure Times", category: "outstation" },
  { slug: "pondicherry-to-chennai-cab-ecr-scenic-route", title: "Pondicherry to Chennai Cab via ECR — Scenic Route Guide", category: "travel" },
  { slug: "acting-driver-chennai-vs-full-cab", title: "Acting Driver Chennai vs Full Cab — Cost & Use Cases", category: "chennai" },
  { slug: "call-driver-chennai-hourly-rates", title: "Call Driver Chennai — Hourly Rates & Package Guide", category: "chennai" },
  { slug: "driver-on-hire-chennai-outstation-allowance", title: "Driver on Hire Chennai for Outstation — Allowance Rules", category: "chennai" },
  { slug: "chauffeur-service-chennai-corporate-events", title: "Chauffeur Service Chennai for Corporate Events & VIP Travel", category: "chennai" },
  { slug: "cab-booking-chennai-otp-login-security", title: "Why OTP Login Matters for Cab Booking Chennai — Security Guide", category: "chennai" },
  { slug: "how-to-cancel-cab-booking-chennai-refund", title: "How to Cancel Cab Booking in Chennai & Refund Policy", category: "chennai" },
  { slug: "chennai-cab-booking-for-senior-citizens", title: "Chennai Cab Booking Tips for Senior Citizens & Hospital Trips", category: "chennai" },
  { slug: "chennai-cab-for-chennai-central-railway-station", title: "Chennai Central Railway Station Cab Pickup & Drop Guide", category: "chennai" },
  { slug: "chennai-egmore-station-taxi-fare", title: "Chennai Egmore Station Taxi Fare & Pre-Booking Tips", category: "fare" },
  { slug: "omr-it-corridor-cab-booking-guide", title: "OMR IT Corridor Cab Booking — Peak Hour Survival Guide", category: "chennai" },
  { slug: "velachery-to-chennai-airport-cab-time", title: "Velachery to Chennai Airport Cab — Time & Fare Estimate", category: "fare" },
  { slug: "tambaram-to-chennai-airport-taxi", title: "Tambaram to Chennai Airport Taxi — Early Morning Booking", category: "airport" },
  { slug: "porur-to-chennai-airport-cab-fare", title: "Porur to Chennai Airport Cab Fare — Sedan & SUV", category: "fare" },
  { slug: "guindy-to-chennai-airport-transfer", title: "Guindy to Chennai Airport Transfer — Trade Show & Hotel Pickups", category: "airport" },
  { slug: "chennai-monsoon-outstation-cab-safety", title: "Chennai Monsoon Outstation Cab Safety Checklist", category: "travel" },
  { slug: "summer-chennai-to-hill-station-cab-tips", title: "Summer Chennai to Hill Station Cab — AC & Hydration Tips", category: "travel" },
  { slug: "diwali-outstation-cab-booking-chennai", title: "Diwali Outstation Cab Booking from Chennai — Book Early Guide", category: "outstation" },
  { slug: "pongal-chennai-to-native-place-cab", title: "Pongal Chennai to Native Place Cab — Peak Season Fares", category: "outstation" },
  { slug: "thaipusam-chennai-to-palani-cab", title: "Thaipusam Chennai to Palani Cab — Pilgrimage Travel Guide", category: "travel" },
  { slug: "sabarimala-season-chennai-cab-options", title: "Sabarimala Season — Chennai Cab Options to Kerala Gateway Cities", category: "travel" },
  { slug: "chennai-cab-for-cruise-terminal-pickup", title: "Chennai Cruise Terminal Cab Pickup — Port Travel Guide", category: "chennai" },
  { slug: "mahabalipuram-day-trip-cab-from-chennai", title: "Mahabalipuram Day Trip Cab from Chennai — Itinerary & Fare", category: "travel" },
  { slug: "kanchipuram-temple-circuit-cab-chennai", title: "Kanchipuram Temple Circuit Cab from Chennai — One Day Plan", category: "travel" },
  { slug: "chettinad-food-trip-cab-from-chennai", title: "Chettinad Food Trip by Cab from Chennai — Route & Stops", category: "travel" },
  { slug: "chennai-to-alleppey-cab-kerala-backwaters", title: "Chennai to Alleppey Cab — Kerala Backwaters Road Trip", category: "travel" },
  { slug: "chennai-to-munnar-cab-hill-station-fare", title: "Chennai to Munnar Cab — Hill Station Fare & Best Route", category: "travel" },
  { slug: "pet-friendly-cab-travel-chennai-tips", title: "Pet-Friendly Cab Travel from Chennai — Booking Tips", category: "chennai" },
  { slug: "child-seat-cab-booking-chennai", title: "Child Seat & Family Cab Booking in Chennai — What to Ask", category: "chennai" },
  { slug: "ladies-safety-cab-booking-chennai", title: "Ladies Safety Tips for Cab Booking in Chennai at Night", category: "chennai" },
  { slug: "cabzii-vs-traditional-travel-agents-chennai", title: "Cabzii vs Traditional Travel Agents in Chennai — Comparison", category: "chennai" },
  { slug: "how-cabzii-shows-upfront-fares", title: "How Cabzii Shows Upfront Cab Fares Before You Pay", category: "fare" },
  { slug: "gst-on-cab-booking-india-explained", title: "GST on Cab Booking in India — What Riders Should Know", category: "fare" },
  { slug: "interstate-permit-outstation-cab-tamil-nadu", title: "Interstate Permit for Outstation Cabs from Tamil Nadu", category: "outstation" },
  { slug: "fastag-tolls-cab-fare-inclusion", title: "FASTag Tolls & Cab Fare — Are They Included?", category: "fare" },
  { slug: "driver-allowance-outstation-cab-explained", title: "Driver Allowance on Outstation Cab — Daily Rate Explained", category: "fare" },
  { slug: "waiting-charges-chennai-local-cab", title: "Waiting Charges on Chennai Local Cab Packages", category: "fare" },
  { slug: "chennai-cab-for-photoshoot-location-hops", title: "Chennai Cab for Pre-Wedding Photoshoot Location Hops", category: "chennai" },
  { slug: "chennai-cab-for-concert-event-transfers", title: "Chennai Cab for Concert & Event Transfers — Post-Show Pickup", category: "chennai" },
  { slug: "chennai-cab-for-medical-appointment-round-trip", title: "Chennai Cab for Medical Appointments — Round Trip Tips", category: "chennai" },
  { slug: "last-minute-airport-cab-chennai", title: "Last-Minute Airport Cab Chennai — Can You Still Book?", category: "airport" },
  { slug: "shared-cab-vs-private-cab-chennai-outstation", title: "Shared Cab vs Private Cab for Chennai Outstation — Pros & Cons", category: "outstation" },
  { slug: "electric-cab-options-chennai-future", title: "Electric Cab Options in Chennai — What to Expect in 2026", category: "chennai" },
  { slug: "chennai-cab-booking-for-tourists-foreign-nationals", title: "Chennai Cab Booking for Tourists & Foreign Nationals", category: "travel" },
  { slug: "chennai-to-pondicherry-bike-vs-cab-travel", title: "Chennai to Pondicherry — Bike vs Cab: Comfort & Cost", category: "travel" },
  { slug: "chennai-to-bangalore-flight-vs-cab", title: "Chennai to Bangalore — Flight vs Cab: Time & Cost Analysis", category: "travel" },
  { slug: "packing-checklist-long-outstation-cab-trip", title: "Packing Checklist for Long Outstation Cab Trips from Chennai", category: "travel" },
  { slug: "highway-rest-stops-chennai-to-bangalore", title: "Best Highway Rest Stops on Chennai to Bangalore Cab Route", category: "travel" },
  { slug: "chennai-cab-scam-avoidance-tips", title: "Chennai Cab Scam Avoidance — Book Verified Taxis Online", category: "chennai" }
];

export const BLOG_TOPIC_CATEGORIES = {
  airport: "Airport taxi searches",
  outstation: "Outstation taxi searches",
  travel: "Travel guides",
  chennai: "Chennai travel keywords",
  fare: "Taxi fare keywords"
};
